version: "2"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.1.1-java8
    container_name: namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "9870:9870"
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.1-java8
    container_name: datanode
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50075:50075"
  spark-master:
    image: bde2020/spark-master:2.3.2-hadoop3.1.1-java8
    container_name: spark-master
    environment:
      CORE_CONF_fs_defaultFS: "hdfs://namenode:8020"
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864"
    env_file:
      - ./hadoop-hive.env
    ports:
      - "8080:8080"
      - "7077:7077"
  spark-worker:
    image: bde2020/spark-worker:2.3.2-hadoop3.1.1-java8
    container_name: spark-worker
    environment:
      SPARK_MASTER: "spark://spark-master:7077"
      SERVICE_PRECONDITION: "spark-master:8080"
    env_file:
      - ./hadoop-hive.env
    ports:
      - "8081:8081"
  spark-example:
    image: bde2020/spark-example:2.3.2-hadoop3.1.1-java8
    container_name: spark-app
    environment:
      SPARK_MASTER: "spark://spark-master:7077"
      SERVICE_PRECONDITION: "spark-master:8080 spark-worker:8081"
    env_file:
      - ./hadoop-hive.env
